In [9]:
from lib import *
from typing import Union

In [2]:
url_video = "http://localhost:3001/videos/tIIgaPo6GV4Fw0UTs11j5S8uZuMbFBRQlbwLY5oRJVwUGmaM8wpWadNp20by7kQ2.webm"


In [50]:
def video2framesSRR(video_path: str, resize: Union[int, int] = (IMG_SIZE, IMG_SIZE)) -> np.array:
    # print("video2frames2")
    cap = cv2.VideoCapture(video_path)
    frames: list = []
    is_there_frame: bool = True
    num_total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
    resampling_rate: int = int(num_total_frames / NUM_FRAMES_PER_VIDEO)
    idf: int = 0
    print(len(frames))
    while is_there_frame and len(frames) < NUM_FRAMES_PER_VIDEO:
        idf += 1
        is_there_frame, frame = cap.read()
        if frame is None: 
            return np.array([])
        #if idf % resampling_rate == 0:
            # grayscale
            # frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            # resize
            # frame = cv2.resize(frame, resize)
        frames.append(frame)
    #assert len(frames)==NUM_FRAMES_PER_VIDEO
    print("video2frames: ", len(frames))
    cap.release()
    return np.array(frames)

In [ ]:
url_video = "http://localhost:3001/videos/SiCyDHbF0GmE123keSi4QPpxprVZDJBKSCrZvl9bzBJCrFUquh01c1gg3ARBTPZk.webm"


In [23]:
cvideo="http://localhost:3001/videos/tIIgaPo6GV4Fw0UTs11j5S8uZuMbFBRQlbwLY5oRJVwUGmaM8wpWadNp20by7kQ2.webm"
svideo="http://localhost:3001/videos/OqTh8BaU1zpxjxIpMGkDaQNbwoFRXeECACy9iunroYhbLt6xVdqaV6Sw8zHxSd0o.webm"

In [39]:
cap = cv2.VideoCapture(cvideo)
frames: list = []
is_there_frame: bool = True
num_total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
print(num_total_frames)
resampling_rate: int = int(num_total_frames / NUM_FRAMES_PER_VIDEO)
print(resampling_rate)
idf: int = 0
print(len(frames))
print(cap)

150.0
9
0
< cv2.VideoCapture 0x7f654f2d2a90>


In [51]:
#frameCvideo = BasicUtil.video2framesSR(cvideo)
frameSvideo = video2framesSRR(svideo)
print(frameSvideo)
#face_lo = face_recognition.face_encodings(frameCvideo[0])[0]
# face_lo2 = face_recognition.face_encodings(frameSvideo[0])[0]

#matches = face_recognition.compare_faces([face_lo], face_lo2)
#print(matches[0])

0
video2frames:  16
[[[[104  91  95]
   [ 83  70  74]
   [118 105 119]
   ...
   [195 199 201]
   [193 201 198]
   [192 200 197]]

  [[ 69  56  60]
   [ 54  41  45]
   [124 111 125]
   ...
   [195 199 201]
   [195 203 200]
   [196 204 201]]

  [[ 51  47  37]
   [ 42  38  28]
   [114 106 121]
   ...
   [198 203 201]
   [194 202 199]
   [193 201 198]]

  ...

  [[146 161 170]
   [139 154 163]
   [140 149 164]
   ...
   [127 138 161]
   [131 146 162]
   [130 145 161]]

  [[151 153 160]
   [144 146 153]
   [158 147 165]
   ...
   [130 134 143]
   [138 133 145]
   [137 132 144]]

  [[171 173 180]
   [167 169 176]
   [184 173 191]
   ...
   [150 154 163]
   [154 149 161]
   [154 149 161]]]


 [[[104  91  95]
   [ 83  70  74]
   [118 105 119]
   ...
   [195 199 201]
   [193 201 198]
   [192 200 197]]

  [[ 69  56  60]
   [ 54  41  45]
   [124 111 125]
   ...
   [195 199 201]
   [195 203 200]
   [196 204 201]]

  [[ 51  47  37]
   [ 42  38  28]
   [114 106 121]
   ...
   [198 203 201]
   [194 

In [5]:
cvideo = video2framesSRR(url_video)

0


[matroska,webm @ 0xd4f4880] Unknown-sized element at 0x74dad inside parent with finite size


video2frames:  16


In [37]:
cvideo

array([], dtype=float64)

In [2]:
try:
    URL = 'http://localhost:3001/videos/'
    video ='2a4l7Lts2071cNEcpGVg2SzzZuASWQFFC8jXZ8Z4WyIzTceg5aoXAkArwEk0MzqW.webm'
    # event = json.loads(msg.decode('utf-8'))
    any_video = URL+video
    model = torchvision.models.resnet18(pretrained=True)
    for e in model.parameters():
        e.requires_grad = False
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    model.fc = nn.Linear(in_features=512, out_features=4, bias=True)
    model.load_state_dict(torch.load("../../models/resnet18_5.pt"))
    model.to(device)
    frames = BasicUtil.video2frames(any_video)
    dataset_x = []
    dataset_x = [*dataset_x, *frames]
    dataset_x = np.array(dataset_x)
    tensor_y_test = torch.as_tensor(np.array([0 for i in range(16)]))
    data_test: MyDataset = MyDataset(dataset_x, tensor_y_test)
    test_loader: DataLoader = DataLoader(dataset=data_test, shuffle=False)
    res = []
    for images, _ in test_loader:
        images = images.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        res.append(np.array(predicted.cpu())[0])
    # return st.mode(res) == 0
    print(st.mode(res))
except Exception as e:
    print(e)
    # return False

init video2frames
num_total_frames 0.0
ModeResult(mode=array([], dtype=float64), count=array([], dtype=float64))


[tcp @ 0xe6a0340] Connection to tcp://localhost:3001 failed: Connection refused
/tmp/ipykernel_7455/4251835917.py:27: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(st.mode(res))


In [40]:
def play_video_capture(video_path: str):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("Error opening video file")
        return

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Display the frame
        cv2.imshow('Video', frame)

        # Exit the loop if 'q' key is pressed
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # Release the VideoCapture object and close the OpenCV windows
    cap.release()
    cv2.destroyAllWindows()

# Example usage
