In [8]:
import os
from dotenv import load_dotenv
load_dotenv()
BROKERS = os.getenv('BROKERS')
print(BROKERS)

localhost:8097,localhost:8098,localhost:8099,localhost:8100


In [9]:
import socket
print( socket.gethostname())

fedora


In [6]:
import cv2
import numpy as np

IMG_SIZE: int = 224
NUM_FRAMES_PER_VIDEO: int = 16
IMG_SIZE: int = 224

# cap = cv2.VideoCapture("../server/public/videos/DIBVp5cVvl5rRPHzOyRVaa1j6FWOiuEWvi9Hy0CO2J1dX2yU26wls4RjFlDKCHsj.webm")
cap = cv2.VideoCapture("http://localhost:3001/videos/GwdQmz26CuItRIppnjPrnnBC5vTdenDsOYXWIKnWa9kMKQ7TOW8k22LxvF7Kgsws.webm")
frames: list = []
is_there_frame: bool = True
num_total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
resampling_rate: int = int(num_total_frames / NUM_FRAMES_PER_VIDEO)
idf: int = 0
while is_there_frame and len(frames) < NUM_FRAMES_PER_VIDEO:
    idf += 1
    is_there_frame, frame = cap.read()
    if frame is None: 
        print(np.array([]))
    if idf % resampling_rate == 0:
        # grayscale
        # frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        # resize
        frame = cv2.resize(frame, (IMG_SIZE, IMG_SIZE))
        frames.append(frame)
# assert len(frames)==NUM_FRAMES_PER_VIDEO
print(np.array(frames))
# Check if camera opened successfully
# if (cap.isOpened()== False): 
#   print("Error opening video stream or file")
 
# # Read until video is completed
# while(cap.isOpened()):
#   # Capture frame-by-frame
#   ret, frame = cap.read()
#   if ret == True:
 
#     # Display the resulting frame
#     cv2.imshow('Frame',frame)
 
#     # Press Q on keyboard to  exit
#     if cv2.waitKey(25) & 0xFF == ord('q'):
#       break
 
#   # Break the loop
#   else: 
#     break
 
# # When everything done, release the video capture object
# cap.release()
 
# # Closes all the frames
# cv2.destroyAllWindows()

[[[[233 218 200]
   [233 218 200]
   [233 218 200]
   ...
   [ 93  93 105]
   [ 91  97 105]
   [ 95 111 111]]

  [[233 218 200]
   [233 218 200]
   [233 218 200]
   ...
   [ 91  91 103]
   [ 91  96 104]
   [ 98 110 111]]

  [[233 218 200]
   [233 218 200]
   [233 218 200]
   ...
   [ 92  92 104]
   [ 91  94 103]
   [101 110 112]]

  ...

  [[ 62  35  34]
   [ 64  39  33]
   [ 64  39  32]
   ...
   [ 86  78 100]
   [ 84  76  98]
   [ 84  76  98]]

  [[ 56  28  28]
   [ 57  31  26]
   [ 57  31  26]
   ...
   [ 88  80 102]
   [ 86  78 100]
   [ 86  78 100]]

  [[ 54  25  28]
   [ 55  28  27]
   [ 55  28  26]
   ...
   [ 88  80 102]
   [ 87  79 101]
   [ 87  79 101]]]


 [[[229 223 192]
   [229 221 194]
   [229 220 197]
   ...
   [ 93  93 105]
   [ 91  97 105]
   [ 95 111 111]]

  [[229 223 192]
   [229 221 194]
   [229 220 197]
   ...
   [ 91  91 103]
   [ 91  96 104]
   [ 98 110 111]]

  [[231 221 194]
   [231 220 195]
   [230 219 198]
   ...
   [ 92  92 104]
   [ 91  94 103]
   [101 110

In [5]:
import cv2
import numpy as np

IMG_SIZE: int = 224
NUM_FRAMES_PER_VIDEO: int = 16
IMG_SIZE: int = 224

# cap = cv2.VideoCapture("../server/public/videos/DIBVp5cVvl5rRPHzOyRVaa1j6FWOiuEWvi9Hy0CO2J1dX2yU26wls4RjFlDKCHsj.webm")
cap = cv2.VideoCapture("http://localhost:3001/videos/GwdQmz26CuItRIppnjPrnnBC5vTdenDsOYXWIKnWa9kMKQ7TOW8k22LxvF7Kgsws.webm")
# frames: list = []
# is_there_frame: bool = True
# num_total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
# resampling_rate: int = int(num_total_frames / NUM_FRAMES_PER_VIDEO)
# idf: int = 0
# while is_there_frame and len(frames) < NUM_FRAMES_PER_VIDEO:
#     idf += 1
#     is_there_frame, frame = cap.read()
#     if frame is None: 
#         print(np.array([]))
#     if idf % resampling_rate == 0:
#         # grayscale
#         # frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
#         # resize
#         frame = cv2.resize(frame, (IMG_SIZE, IMG_SIZE))
#         frames.append(frame)
# # assert len(frames)==NUM_FRAMES_PER_VIDEO
# print(np.array(frames))
# Check if camera opened successfully
# if (cap.isOpened()== False): 
#   print("Error opening video stream or file")
 
# Read until video is completed
while(cap.isOpened()):
  # Capture frame-by-frame
  ret, frame = cap.read()
  if ret == True:
 
    # Display the resulting frame
    cv2.imshow('Frame',frame)
 
    # Press Q on keyboard to  exit
    if cv2.waitKey(25) & 0xFF == ord('q'):
      break
 
  # Break the loop
  else: 
    break
 
# When everything done, release the video capture object
cap.release()
 
# Closes all the frames
cv2.destroyAllWindows()